version : "3"
services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    volumes: 
      - ./:/app
      - /app/node_modules
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=mayur
      - MONGO_PASSWORD=mayur
      - SESSION_SECRET=secret
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mayur
      MONGO_INITDB_ROOT_PASSWORD: mayur
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db: